# Generated by Django 5.0.4 on 2024-05-01 10:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='voiture',
            field=models.ManyToManyField(blank=True, related_name='owners', to='api.voiture'),
        ),
        migrations.AlterField(
            model_name='park',
            name='id',
            field=models.CharField(default=uuid.UUID('19dfb64c-f42c-4cb6-96a1-3e3c53129da6'), editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
