# Generated by Django 5.0.4 on 2024-05-01 14:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_voiture_matricule_alter_park_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='id',
            field=models.CharField(default=uuid.UUID('7baffc44-ab12-4633-85ec-07cb3d4b9ba5'), editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
