# Generated by Django 5.0.4 on 2024-05-02 08:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_park_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='cout',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='park',
            name='dateDebut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='park',
            name='id',
            field=models.CharField(default=uuid.UUID('d482b524-21d0-490a-a657-bb2571e828ba'), editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
