# Generated by Django 5.0.4 on 2024-05-02 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_park_datedebut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='dateDebut',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 2, 8, 36, 52, 210261, tzinfo=datetime.timezone.utc), unique=True),
        ),
    ]
