# Generated by Django 5.0.4 on 2024-05-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_park_voiture'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
