# Generated by Django 5.0.4 on 2024-05-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_voiture_model_voiture_numero_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='marque',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='numero_type',
            field=models.CharField(default='000000000000000', max_length=15, unique=True),
        ),
    ]
