# Generated by Django 5.0.4 on 2024-05-13 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_voiture_numero_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiture',
            name='numero_type',
        ),
    ]
