# Generated by Django 5.0.4 on 2024-05-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_voiture_numero_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='numero_type',
            field=models.CharField(default=1, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
