# Generated by Django 4.2.3 on 2024-04-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('localisation', models.URLField(blank=True, null=True)),
                ('commune', models.CharField(choices=[('Alger_Centre', 'Alger Centre'), ('Sidi_Mhamed', 'Sidi Mhamed'), ('El_Madania', 'El Madania'), ('Belouizdad', 'Belouizdad'), ('Bab_El_Oued', 'Bab El Oued'), ('Bologhine', 'Bologhine'), ('Casbah', 'Casbah'), ('Oued_Koriche', 'Oued Koriche'), ('Bir_Mourad_Rais', 'Bir Mourad Rais'), ('El_Biar', 'El Biar'), ('Bouzareah', 'Bouzareah'), ('Birkhadem', 'Birkhadem'), ('El_Harrach', 'El Harrach'), ('Baraki', 'Baraki'), ('Oued_Smar', 'Oued Smar'), ('Bourouba', 'Bourouba'), ('Hussein_Dey', 'Hussein Dey'), ('Kouba', 'Kouba'), ('Bachedjerah', 'Bachedjerah'), ('Dar_El_Beida', 'Dar El Beida'), ('Bab_Azzouar', 'Bab Azzouar'), ('Ben_Aknoun', 'Ben Aknoun'), ('Dely_Ibrahim', 'Dely Ibrahim'), ('El_Hammamet', 'El Hammamet'), ('Rais_Hamidou', 'Rais Hamidou'), ('Djasr_Kasentina', 'Djasr Kasentina'), ('El_Mouradia', 'El Mouradia'), ('Hydra', 'Hydra'), ('Mohammadia', 'Mohammadia'), ('Bordj_El_Kiffan', 'Bordj El Kiffan'), ('El_Magharia', 'El Magharia'), ('Beni_Messous', 'Beni Messous'), ('Les_Eucalyptus', 'Les Eucalyptus'), ('Birtouta', 'Birtouta'), ('Tassala_El_Merdja', 'Tassala El Merdja'), ('Ouled_Chebel', 'Ouled Chebel'), ('Sidi_Moussa', 'Sidi Moussa'), ('Ain_Taya', 'Ain Taya'), ('Bordj_El_Bahri', 'Bordj El Bahri'), ('Marsa', 'Marsa'), ('Haraoua', 'Haraoua'), ('Rouiba', 'Rouiba'), ('Reghaia', 'Reghaia'), ('Ain_Benian', 'Ain Benian'), ('Staoueli', 'Staoueli'), ('Zeralda', 'Zeralda'), ('Mahelma', 'Mahelma'), ('Rahmania', 'Rahmania'), ('Souidania', 'Souidania'), ('Cheraga', 'Cheraga'), ('Ouled_Fayet', 'Ouled Fayet'), ('El_Achour', 'El Achour'), ('Draria', 'Draria'), ('Douera', 'Douera'), ('Baba_Hassen', 'Baba Hassen'), ('Khracia', 'Khracia'), ('Saoula', 'Saoula')], max_length=100)),
                ('capacite', models.IntegerField(blank=True, default=10, null=True)),
            ],
        ),
    ]
