# Generated by Django 5.0.4 on 2024-05-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QrCodeGenSec', '0002_alter_parking_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parking',
        ),
    ]
